name: CI on PR creation or update.
on:
  pull_request:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --no-tags --prune --depth=5 origin master
      - name: Install packages
        run: npm ci
      - name: Run linter on affected
        run: npm run affected:lint -- --base=origin/master
      - name: Run unit tests on affected
        run: npm run affected:test -- --base=origin/master
      - name: Run and e2e tests on affected
        run: npm run affected:e2e -- --base=origin/master
      - name: Run build on affected
        run: npm run affected:build -- --base=origin/master
